A new gate_sequence_product, Simulator and Results Class!
qutip/qutip pull request #1331
Opened 2020-07-28 06:00 UTC by sarsid

**Checklist**
Thank you for contributing to QuTiP! Please make sure you have finished the following tasks before opening the PR.

- [ ] Please read [Contributing to QuTiP Development](https://github.com/qutip/qutip-doc/blob/master/CONTRIBUTING.md)
- [ ] Contributions to qutip should follow the [pep8 style](https://www.python.org/dev/peps/pep-0008/).
You can use [pycodestyle](http://pycodestyle.pycqa.org/en/latest/index.html) to check your code automatically
- [ ] Please add tests to cover your changes if applicable.
- [ ] If the behavior of the code has changed or new feature has been added, please also update the [documentation](https://github.com/qutip/qutip-doc) and the [notebook](https://github.com/qutip/qutip-notebooks). Feel free to ask if you are not sure.

**Description**
There are three major parts to this PR (more or less interlinked): 

- Adds `Simulator` class to abstract away circuit run functionality. This enables future contributors to add to exact simulation (and potentially other ways of simulation) easily. It also has a `step` function which allows to go over the circuit step-by-step which could enable interesting visualisations! 
- Adds `Result` class as a wrapper around results obtained from circuit simulations. 
- Adds a more efficient mode to `gate_sequence_product` function which allows for faster pre-computation of unitaries! 

**Changelog**
Added `Simulator`, `Result` class 
Added new mode to `gate_sequence_product`, `QubitCircuit.propagators`

2020-09-02 08:28 UTC, BoxiLi commented
@sarsid, could you push the code you have on this PR? I'd like to get it merged and use the Result class you defined also in the Processor class ;)

2020-09-03 01:52 UTC, sarsid commented on qutip/qip/operations/gates.py
> +def _gate_sequence_product(U_list, ind_list, expand_N=None):
Yep, thanks for spotting this, do not need this parameter anymore

2020-09-03 01:53 UTC, sarsid commented on qutip/qip/operations/gates.py
> +        return _gate_sequence_product(U_list, inds_list)
I have a few comments on this in the documentation.

2020-09-03 01:54 UTC, sarsid commented on qutip/qip/circuit.py
> +        U_list: list of Qobj, optional
I kept *U_list* argument in the optional case where a user calculated it for some reason before hand. Should we remove it? Maybe not needed anymore. Don't think it goes well with the other options anymore.

2020-09-03 17:28 UTC, sarsid commented on qutip/qip/operations/gates.py
> +def _gate_sequence_product_expanded(U_list, left_to_right=True):
Agreed

2020-09-04 14:41 UTC, sarsid commented
@BoxiLi should be good to go, added more inline docs, plus some examples in `gates.py`

2020-09-07 11:54 UTC, BoxiLi requested changes
Thanks @sarsid . Looks good to me, except for a remaining `print`. With this removed, it is ready for merging.

2020-09-07 11:54 UTC, BoxiLi commented on qutip/qip/operations/gates.py
> +    print(overall_inds)
I guess this is only for local test

2020-09-07 14:12 UTC, sarsid commented on qutip/qip/operations/gates.py
> +    print(overall_inds)
done

2020-09-07 18:07 UTC, BoxiLi approved these changes

2020-09-30 15:24 UTC, merged

2020-10-01 15:11 UTC, nathanshammah commented
Well done @sarsid. Could you make sure that the documentation is still up to date? Adding something in the Users Guide about this would be very helpful.

2020-10-05 03:59 UTC, sarsid commented
Thanks @nathanshammah, I believe that most of the docs are up to date in the PR https://github.com/qutip/qutip-doc/pull/117, I will make sure to make a couple of changes Boxi suggested before it's ready to merge.