Add new color_style argument to hinton() (#1595).
qutip/qutip pull request #1674
Opened 2021-09-25 02:45 UTC by cgranade

**Description**
This PR adds thresholding and phase color styles to `qutip.visualization.hinton`.

**Related issues or PRs**
- #1595

**Changelog**
Hinton diagrams now support threshold, scaled, and phase color styles.

2021-11-07 22:19 UTC, BoxiLi requested changes
Sorry for the delay and thanks for making the PR. The threshold style looks good.
However, the phase style is not working correctly because `w` is already the absolute value when calling `_blob`. I added some changes in my branch to make it work https://github.com/BoxiLi/qutip/blob/hinton_color/qutip/visualization.py
I can push to this PR if you would like me to.

2021-12-06 14:36 UTC, hodgestar commented
@BoxiLi Would you mind pushing your fixes to this PR and perhaps we can tidy up the last few things and merge it?

2021-12-12 21:21 UTC, BoxiLi commented
The following can be used for testing: @hodgestar 
```
import qutip

dm = qutip.rand_dm(4)
fig, ax = qutip.hinton(dm)
fig.show()

qutip.settings.colorblind_safe = True
fig, ax = qutip.hinton(dm, color_style="threshold")
fig.show()
qutip.settings.colorblind_safe = False

fig, ax = qutip.hinton(dm, color_style="phase")
fig.show()
```

2022-01-09 12:08 UTC, BoxiLi commented
@hodgestar Would you like to have a review?

2022-01-10 11:04 UTC, hodgestar approved these changes

2022-01-10 11:06 UTC, hodgestar commented
@BoxiLi @cgranade Looks good to me -- thank you! I've marked this for inclusion in 4.7 and will merge.

2022-01-10 11:06 UTC, merged