Edit stochastic docs
qutip/qutip pull request #1743
Opened 2021-12-20 05:46 UTC by Leo-am

**Description**

Edited the user guide documentation for Stochastic solvers. Text, equations, and example updated.

**Related issues or PRs**
Related to issue #1706.

**Changelog**

- Improved explanation of stochastic equation solvers.
- Added links for notebooks with examples for stochastic solvers.
- Added links to API documentation for smesolve, ssesolve, general_stochastic.
- New example highlighting the differences between result.expect and result.measurement.
- Added reference to Quantum Measurement and Control, Wiseman & Milburn (2009).

2021-12-21 23:28 UTC, Ericgig commented
Thank you Leo-am, I took a quick look and it's nice.
We will do a proper review in January.

2022-01-17 21:33 UTC, Ericgig commented on doc/guide/dynamics/dynamics-stochastic.rst
> +    D[A] \rho = \frac{1}{2} \left[2 A \rho C^\dagger
The `C^\dagger` should be `A^\dagger`.

2022-01-17 22:25 UTC, Ericgig requested changes
Thank you for the rewriting, look great.
The example is a lot better than what it was.
The equations are clear, but there are a few typos to fix.

2022-01-18 01:00 UTC, Leo-am commented on doc/guide/dynamics/dynamics-stochastic.rst
> +    D[A] \rho = \frac{1}{2} \left[2 A \rho C^\dagger
Typo fixed.

2022-01-18 01:00 UTC, Leo-am commented on doc/guide/dynamics/dynamics-stochastic.rst
> +    d_2 = S_n - \frac{e_n}{2}.
Change made.

2022-01-18 01:00 UTC, Leo-am commented on doc/guide/dynamics/dynamics-stochastic.rst
> +    d_1 = -iH - \frac{1}{2} \left(S_n^\dagger S_n - e_n S_n + \frac{e_i^2}{4}  \right),
Change made.

2022-01-18 01:02 UTC, Leo-am commented
Thanks for reviewing, Eric. All typos are fixed.

2022-01-18 16:37 UTC, Ericgig approved these changes

2022-01-19 10:38 UTC, hodgestar commented
Thanks @Leo-am for making these docs much better and thank you @Ericgig for reviewing. Merging.

2022-01-19 10:38 UTC, merged