Add QuTiP to compare QHSO and the transmon
qutip/qutip pull request #1790
Opened 2022-02-01 14:58 UTC by DRA-chaos

Added a utility comparison between the QHSO and Transmon

2022-02-01 15:54 UTC, Ericgig commented
Hi DRA-chaos, thank you for the PR, but we keep notebooks example in another repo: https://github.com/qutip/qutip-notebooks. Could you move your PR there. Also please don't use space in file names.

The wording improvement in the readme is nice, can you leave just those changes here.

2022-02-02 11:33 UTC, hodgestar requested changes
Thank you for removing the notebook -- is there a qutip-notebook PR for it yet?

I declined most of the changes left, but not all of them.

2022-02-02 11:33 UTC, hodgestar commented on README.md
> +The QuTiP library uses Numpy, Scipy, and Cython packages as numerical backends, and Matplotlib for graphical output.
```suggestion
QuTiP is open-source software for simulating the dynamics of closed and open quantum systems.
It uses the excellent Numpy, Scipy, and Cython packages as numerical backends, and graphical output is provided by Matplotlib.
```
"software" is an uncountable noun and so does not take an article. Praising numpy, SciPy and Cython shows we're grateful to those projects and sets a good tone, so I'd like to keep it. Using a slightly different phrasing when mentioning Matplotlib makes the sentence less repetitive, so I'd like to keep it that way.

2022-02-02 11:33 UTC, hodgestar commented on README.md
> +QuTiP does not charge any licensing fees and hence is ideal for exploring quantum mechanics in research as well as in the classroom.
```suggestion
Being free of any licensing fees, QuTiP is ideal for exploring quantum mechanics in research as well as in the classroom.
```
I think the new phrasing is a slight degradation, so I'd like to keep the original.

2022-02-02 11:33 UTC, hodgestar approved these changes

2022-02-02 11:35 UTC, merged

2022-02-02 11:36 UTC, hodgestar commented
@DRA-chaos Thank you for the small README fixes. Looking forward to the qutip-notebook PR.