Fix fidelity for pure states
qutip/qutip pull request #1964
Opened 2022-07-29 10:15 UTC by PierreGuilmin

**Description**
The previous code converted both states to density matrices, which is both inefficient and numerically inaccurate. We propose to use the reduced fidelity formula for pure states, given by the modulus of their inner product.

**Related issues or PRs**
Related to #361 and #925.

Reusing @lucainnocenti example (https://github.com/qutip/qutip/issues/925#issuecomment-542318121):
```python
import qutip as qt
import numpy as np

A = qt.Qobj(np.array([
    0.867314655330313 - 0.4576338188944636j,
    0.17267952805615244 - 0.09111291375544905j,
    0.013020232894921149 -0.006875138252288391j
]))
B = qt.Qobj(np.array([
    0.9806443568092577, 0.19524328915024022, 0.014720852555238875
]))

fid1 = np.abs(np.vdot(A.full(), B.full()))
fid2 = np.abs((A.dag() * B)[0, 0])
fid3 = np.abs(A.overlap(B))
fid_qt = qt.fidelity(A, B)
print(f'Correct:\n{fid1}\n{fid2}\n{fid3}')
print(f'Incorrect:\n{fid_qt}')
```
```
Correct:
0.9999999999849929
0.9999999999849929
0.9999999999849929
Incorrect:
1.0000000028441378
```

Note that this PR does not fix https://github.com/qutip/qutip/issues/925#issuecomment-542318121 proposition to perform the general computation using `scipy.linalg.svdvals` at the cost of computing the square root of both matrices.

2022-07-29 18:53 UTC, Ericgig requested changes
Looks good, thank you.

The changes file name is off by one, could you rename it.

2022-07-31 09:27 UTC, PierreGuilmin commented
Sorry, fixed 🙇‍♂️

2022-07-31 10:02 UTC, hodgestar commented on doc/changes/1964.bugfix
> +Fix fidelity for pure states.
```suggestion
Change fidelity(A, B) to use the reduced fidelity formula for pure states which is more numerically efficient and accurate.
```

2022-07-31 10:03 UTC, hodgestar approved these changes

2022-07-31 11:13 UTC, hodgestar commented
Thanks @PierreGuilmin!

I made the changelog message a bit more detailed and will merge now.

2022-07-31 11:13 UTC, merged