Draft: Reduce qutip import time by setting logger names
qutip/qutip pull request #1980
Opened 2022-08-18 22:06 UTC by eendebakpt

**Checklist**
Thank you for contributing to QuTiP! Please make sure you have finished the following tasks before opening the PR.

- [ ] Please read [Contributing to QuTiP Development](http://qutip.org/docs/latest/development/contributing.html)
- [ ] Contributions to qutip should follow the [pep8 style](https://www.python.org/dev/peps/pep-0008/).
You can use [pycodestyle](http://pycodestyle.pycqa.org/en/latest/index.html) to check your code automatically
- [ ] Please add tests to cover your changes if applicable.
- [ ] If the behavior of the code has changed or new feature has been added, please also update the documentation in the `doc` folder, and the [notebook](https://github.com/qutip/qutip-notebooks). Feel free to ask if you are not sure.
- [ ] Include the changelog in a file named: `doc/changes/<PR number>.<type>` 'type' can be one of the following: feature, bugfix, doc, removal, misc, or deprecation (see [here](http://qutip.org/docs/latest/development/contributing.html#Changelog%20Generation) for more information).

Delete this checklist after you have completed all the tasks. If you have not finished them all, you can also open a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to let the others know this on-going work and keep this checklist in the PR description.

**Description**
Importing qutip takes a long time. On a Windows system import takes almost 3 seconds. The import time can be analyzed with [importtime-waterfall](https://github.com/asottile/importtime-waterfall). A large part of the time is spend in importing external packages (scipy, IPython, matplotilib), but also qutip itself adds to the import time.

This PR reduces the import time by setting the logger names in 4 submodules explicitly. 
Benchmark:
```
python -c "import time; import matplotlib; import IPython; import scipy; t0=time.time(); import qutip; dt=time.time()-t0; print(f'{dt*1e3:.2f} ms')"
``` 
Results:
```
dev.major: 1996.52 ms
PR: 1510.06 ms
```

2022-08-18 22:35 UTC, hodgestar commented on doc/changes/1980.feature.py
> +Improve qutip import times
```suggestion
Improve qutip import times by setting logger names explicitly.
```

2022-08-18 22:36 UTC, hodgestar requested changes
Thanks @eendebakpt. This is a great improvement for a small change. I left one suggestion for adding a bit more of a description to the change log, but I think it looks good to merge. Are there any more changes you'd like to make?

2022-08-18 22:37 UTC, hodgestar commented
For QuTiP v5 we're thinking of implementing https://scientific-python.org/specs/spec-0001/ (i.e. for the dev.major branch) but we haven't gotten around to it yet.

2022-08-18 22:40 UTC, eendebakpt commented
> Thanks @eendebakpt. This is a great improvement for a small change. I left one suggestion for adding a bit more of a description to the change log, but I think it looks good to merge. Are there any more changes you'd like to make?

I am creating a similar PR against dev.major. Perhaps there are more optimizations to be done (have not checked yet), but I think it is better to put it in a seperate PR.

2022-08-18 22:42 UTC, hodgestar commented
@eendebakpt Happy for me to merge this PR?

2022-08-19 09:48 UTC, hodgestar approved these changes
Thanks @eendebakpt.

2022-08-19 09:48 UTC, merged