Add missing Dense specialisations
qutip/qutip pull request #2008
Opened 2022-10-14 20:42 UTC by Ericgig

**Description**
`Dense` was missing some dispatch specialisations:
`isherm`, `isdiag`, `inner`, `inner_op`, `pow`, `indices` and `dimensions`.
Some of them are quite commonly used:
- `isherm` is called in a few method of `Qobj` like `eigenstates`.
- `inner` is used in `Qobj.__matmul__` between `bra` and `ket`.

Tests for new functions are added.
For `isherm`, it was already tested for Dense, but relied on the automatic conversion of the dispatcher.

Also fix some docstings which used `Arguments` instead of `Parameters`.

2022-10-31 19:29 UTC, Ericgig commented
Also fixed dense matmul to use `zgemv` for `oper@ket`.
In the `oper @ ket` [matmul scaling benchmarks](https://qutip.org/qutip-benchmark/s_matmul.html), `Dense` is slower than `numpy`. Our dense data layer used `zgemm` for both matrix @ matrix and matrix @ vector operations. By switching to `zgemv` we get closer to numpy's times: faster in `C` format but slower in `Fortran`.
`bra@oper` still use `zgemm`.

2022-12-02 15:48 UTC, hodgestar requested changes
I think we can improve is_herm_dense, but otherwise looks great.

2022-12-02 15:48 UTC, hodgestar commented on qutip/core/data/properties.pyx
> +        for col in range(size):
```suggestion
        for col in range(row + 1):
```
We could just check the lower triangle plus diagonal.

2022-12-02 16:09 UTC, hodgestar approved these changes

2022-12-02 16:54 UTC, merged