Add `Qobj.get` to obtain the data in common type
qutip/qutip pull request #2141
Opened 2023-03-29 14:04 UTC by Ericgig

**Description**
I think that with the different data type a `Qobj`  can contain, it would be useful to be able get the underlying data (ndarray, csr_matrix, jax.Array, etc.) easily from the `Qobj`. I added the method `Qobj.get(copy)` for that.

I allow direct access to the object in case it's needed for auto-differentiation or other advanced features.

I am open to a better name than `get` if it's too generic.

2023-04-05 09:23 UTC, hodgestar requested changes
I like this new interface and I'm fairly happy with the name `extract` unless someone thinks of a better option.

The doc strings also need some updating.

2023-04-05 09:23 UTC, hodgestar commented on qutip/core/data/extract.py
> +        return matrix.as_ndarray()
```suggestion
def extract_dense(matrix, format=None, copy=True):
    """
    Return an array representation of the Dense data object.

    Parameters
    ----------
    matrix : Data
        The matrix to convert to the given format.

    format : str {"ndarray"}, default="ndarray"
        Type of the output.

    copy : bool, default: True
        Whether to return a copy of the data. If False,
        a view of the data is returned when possible.
    """
    if format not in [None, "ndarray"]:
        raise ValueError(
            f"Dense data instances do not support being extracted to format {format!r}"
        )
    if copy:
        return matrix.to_array()
    else:
        return matrix.as_ndarray()
```

2023-04-05 09:23 UTC, hodgestar commented on qutip/core/data/extract.py
> +get = _Dispatcher(
```suggestion
extract = _Dispatcher(
```

2023-04-05 09:23 UTC, hodgestar commented on qutip/core/data/extract.py
> +    name='get',
```suggestion
    name='extract',
```

2023-04-07 13:00 UTC, AGaliciaMartinez commented
What about `data_as`, `get_as` or `extract_as`? I think adding `as` to any of the method names could facilitate understanding what this method does without reading documentation. I personally prefer `data_as` given that `data` is already a method for qobj.

2023-04-19 12:55 UTC, Ericgig commented
@hodgestar, is the current naming fine for you? I

2023-04-19 14:40 UTC, hodgestar approved these changes
Sorry, I think I missed the last commit. Happy with the new name.

2023-04-19 15:01 UTC, merged