Make `kraus_to_choi` faster by using numpy
qutip/qutip pull request #2283
Opened 2024-01-05 01:50 UTC by theodotk

`np.tensordot` is faster than a triple loop. On my applications the function became up to 100 times faster.

Also, the way to handle `dims` of the Choi matrix was incorrect (or I misunderstood something). It is explained in the comments.

This was coded in collab with [Rafael Haenel](https://github.com/rafaelha).

Also, please, could you make a release of the qutip 4 with all the new changes after this PR passes?

2024-01-08 14:45 UTC, Ericgig requested changes
Thank for for the optimization.

The test failure for 3.6 is due to `np.asarray(Qobj)` failing with old version of numpy.
We don't want to remove support for older version of python and numpy for v4.
Could you fix it by using `Qobj.full` as you did in the v5 version.

Other than that, it's looking good.

Other tests failure are not related to your changes.

2024-01-08 18:59 UTC, Ericgig approved these changes

2024-01-11 14:19 UTC, merged

2024-01-11 19:18 UTC, theodotk commented
Thanks for merging!
Is it possible to make a release of qutip 4? Or, if you have a set release calendar, when to expect it?

2024-01-18 16:31 UTC, Ericgig commented
Hi @theodotk, the 4.7.4 release is in progress.