Add coo format
qutip/qutip pull request #2314
Opened 2024-02-02 15:00 UTC by Matt-Ord

**Checklist**
Thank you for contributing to QuTiP! Please make sure you have finished the following tasks before opening the PR.

- [x] Please read [Contributing to QuTiP Development](http://qutip.org/docs/latest/development/contributing.html)
- [] Contributions to qutip should follow the [pep8 style](https://www.python.org/dev/peps/pep-0008/).
You can use [pycodestyle](http://pycodestyle.pycqa.org/en/latest/index.html) to check your code automatically
- [x] Please add tests to cover your changes if applicable.
- [x] If the behavior of the code has changed or new feature has been added, please also update the documentation in the `doc` folder, and the [notebook](https://github.com/qutip/qutip-tutorials). Feel free to ask if you are not sure.
- [ ] Include the changelog in a file named: `doc/changes/<PR number>.<type>` 'type' can be one of the following: feature, bugfix, doc, removal, misc, or deprecation (see [here](http://qutip.org/docs/latest/development/contributing.html#changelog-generation) for more information).

Delete this checklist after you have completed all the tasks. If you have not finished them all, you can also open a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to let the others know this on-going work and keep this checklist in the PR description.

**Description**
Describe here the proposed change.

**Related issues or PRs**
Please mention the related issues or PRs here. If the PR fixes an issue, use the keyword fix/fixes/fixed followed by the issue id, e.g. fix #1184

2024-02-04 11:02 UTC, Matt-Ord commented
@Ericgig would you also be able to approve workflows for this - it should also be ready to review

2024-02-07 16:56 UTC, Ericgig reviewed
I started looking at it.

As few general comments:
- `idxint` vs `size_t`. `idxint` is used for the shape of the matrix, per default it is 32bit to play nice with scipy. This mean that the max matrix size is (2**32, 2**32), but then for dense array, the data pointer can go up to 2**64. Thus it is not safe to change the types.
For COO, you do not check if nnz overflow `idxint` which could eventually cause errors. 

- For many operations, you allow the creation of repeated elements. These repetition could easily be accumulated and without any clean up, I don't see how COO would be better than CSR in real use cases.

- Focus on the COO layer only. Please revert changes in explicit_rk, sode, ssystem, qobjevo... We made it such as adding a new data layer could be done in a separate project without having to touch the existing code base. It's not perfect, no auto-differentiation for brmesolve with qutip-jax as is, but you should not need to update these files in this PR.

Lastly, please add commit to this PR instead of force-pushing a single commit. This allows me to focus on the changes only. 

I will run the tests when I will have at least skimmed through everything.

2024-02-07 16:56 UTC, Ericgig commented on qutip/core/data/matmul.pyx
> +                out._nnz += 1
While I don't dislike the use of `expand` here, you can easily compute the output's nnz since you allow duplicate entries.

2024-02-07 16:56 UTC, Ericgig commented on qutip/solver/sode/_sode.pyx
> +        cdef Dense new_state = _data.to(Dense, _data.add(state, a, dt))
This solver should work with any data type, not just dense.

2024-02-07 16:56 UTC, Ericgig commented on qutip/core/data/add.pyx
> +cpdef Dense iadd_dense_dense(Dense left, Dense right, double complex scale=1):
When only one data type is used, the function name is {operation}_{dtype}.

2024-02-07 16:56 UTC, Ericgig commented on qutip/core/data/add.pyx
> +cpdef Dense iadd_dense(Dense left, Data right, double complex scale=1):
For function with multiple type: `{operation}_{first_dtype}_{second_dtype}_..._{out_dtype}`

```suggestion
cpdef Dense iadd_dense_data_dense(Dense left, Data right, double complex scale=1):
```

2024-02-07 16:56 UTC, Ericgig commented on qutip/core/data/add.pyx
> +cpdef Dense iadd_dense_data(Dense left, Data right, double complex scale=1):
This can be inline in the function below.

2024-02-08 17:35 UTC, Ericgig requested changes
Thank @Matt-Ord,
Finished reading through it.

As I said, creating a full data layer is lot of work. This is a good start, but feel a little bit rushed. 

While we can add specialisation one at a time, to be in qutip/qutip, it need to be mostly complete. It need to at least have everything needed to run `mesolve`. 
Please add `kron` `expect_super` and `project`.

Many of the functions you wrote are not added. (`add_coo`, `mul_coo`, ...).

2024-02-08 17:35 UTC, Ericgig commented on qutip/core/data/coo.pyx
> +    return out
This is not sorting...

2024-02-12 19:31 UTC, Matt-Ord commented
Thanks for the review, and sorry for the slow response - I still intend to get this in a more complete state but it will take some time. I am happy to add kron expect_super and project if that is all that is required but I don't want to get into the trap of doing everything in one massive pr. I don't really see the issue with doing any other specializations in a follow up pr (I could even remove the current specializations if that makes it easier to get it merged incrementally...)

2024-02-13 22:13 UTC, Ericgig commented
It's fine to not split the PR in too many chunks.
Yes it's easier to review, but I don't want to have it half implemented/merged at release, which is coming soon.
You could just add `kron` here. The other can be implemented using matmul and can wait.

It's fine to take some time. Just ping me when you want a re-review.

2024-02-15 13:47 UTC, Ericgig commented
Either `nnz` return `size_t` or raise an error when allocating matrix with too many elements.

2025-02-26 05:26 UTC, closed without merging